import React from 'react'

function About() {
  return (
    <div className='about'>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut fuga enim autem ipsum maxime aut neque dicta eius facere debitis eligendi deserunt sapiente quia aspernatur minus, doloremque delectus inventore cumque praesentium corrupti expedita incidunt accusamus voluptatem natus. Expedita voluptates nulla debitis a, itaque fugiat maxime sequi placeat omnis eaque molestiae repellat quibusdam ducimus quam eos dicta incidunt eum similique illum distinctio, molestias quas. Veniam distinctio quisquam fugiat id ad cum ducimus, cumque repellendus earum dignissimos a veritatis laboriosam sunt impedit nostrum laborum natus deserunt quaerat numquam commodi reiciendis voluptates eum. Quo blanditiis in architecto. Porro sapiente architecto voluptates incidunt nostrum.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut fuga enim autem ipsum maxime aut neque dicta eius facere debitis eligendi deserunt sapiente quia aspernatur minus, doloremque delectus inventore cumque praesentium corrupti expedita incidunt accusamus voluptatem natus. Expedita voluptates nulla debitis a, itaque fugiat maxime sequi placeat omnis eaque molestiae repellat quibusdam ducimus quam eos dicta incidunt eum similique illum distinctio, molestias quas. Veniam distinctio quisquam fugiat id ad cum ducimus, cumque repellendus earum dignissimos a veritatis laboriosam sunt impedit nostrum laborum natus deserunt quaerat numquam commodi reiciendis voluptates eum. Quo blanditiis in architecto. Porro sapiente architecto voluptates incidunt nostrum.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut fuga enim autem ipsum maxime aut neque dicta eius facere debitis eligendi deserunt sapiente quia aspernatur minus, doloremque delectus inventore cumque praesentium corrupti expedita incidunt accusamus voluptatem natus. Expedita voluptates nulla debitis a, itaque fugiat maxime sequi placeat omnis eaque molestiae repellat quibusdam ducimus quam eos dicta incidunt eum similique illum distinctio, molestias quas. Veniam distinctio quisquam fugiat id ad cum ducimus, cumque repellendus earum dignissimos a veritatis laboriosam sunt impedit nostrum laborum natus deserunt quaerat numquam commodi reiciendis voluptates eum. Quo blanditiis in architecto. Porro sapiente architecto voluptates incidunt nostrum.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut fuga enim autem ipsum maxime aut neque dicta eius facere debitis eligendi deserunt sapiente quia aspernatur minus, doloremque delectus inventore cumque praesentium corrupti expedita incidunt accusamus voluptatem natus. Expedita voluptates nulla debitis a, itaque fugiat maxime sequi placeat omnis eaque molestiae repellat quibusdam ducimus quam eos dicta incidunt eum similique illum distinctio, molestias quas. Veniam distinctio quisquam fugiat id ad cum ducimus, cumque repellendus earum dignissimos a veritatis laboriosam sunt impedit nostrum laborum natus deserunt quaerat numquam commodi reiciendis voluptates eum. Quo blanditiis in architecto. Porro sapiente architecto voluptates incidunt nostrum.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut fuga enim autem ipsum maxime aut neque dicta eius facere debitis eligendi deserunt sapiente quia aspernatur minus, doloremque delectus inventore cumque praesentium corrupti expedita incidunt accusamus voluptatem natus. Expedita voluptates nulla debitis a, itaque fugiat maxime sequi placeat omnis eaque molestiae repellat quibusdam ducimus quam eos dicta incidunt eum similique illum distinctio, molestias quas. Veniam distinctio quisquam fugiat id ad cum ducimus, cumque repellendus earum dignissimos a veritatis laboriosam sunt impedit nostrum laborum natus deserunt quaerat numquam commodi reiciendis voluptates eum. Quo blanditiis in architecto. Porro sapiente architecto voluptates incidunt nostrum.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut fuga enim autem ipsum maxime aut neque dicta eius facere debitis eligendi deserunt sapiente quia aspernatur minus, doloremque delectus inventore cumque praesentium corrupti expedita incidunt accusamus voluptatem natus. Expedita voluptates nulla debitis a, itaque fugiat maxime sequi placeat omnis eaque molestiae repellat quibusdam ducimus quam eos dicta incidunt eum similique illum distinctio, molestias quas. Veniam distinctio quisquam fugiat id ad cum ducimus, cumque repellendus earum dignissimos a veritatis laboriosam sunt impedit nostrum laborum natus deserunt quaerat numquam commodi reiciendis voluptates eum. Quo blanditiis in architecto. Porro sapiente architecto voluptates incidunt nostrum.</p>
    </div>
  )
}

export default About
